version: "3.9"

services:
  additioner:
    image: golang:latest
    container_name: additioner
    ports:
      - "8081:80"
    volumes:
      - ./additioner/html:/usr/share/nginx/html
    networks:
      - app_network

  multiplicationer:
    image: golang:latest
    container_name: multiplicationer
    working_dir: /app
    volumes:
      - ./multiplicationer:/app
    command: python -m http.server 8000
    ports:
      - "8082:8000"
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
